[package]
name = "dropper"
version = "0.1.0"
edition = "2021"

[features]
windows-service = []

[build-dependencies]
embed-resource = { workspace = true }

[dependencies]
obfstr = { workspace = true }
