[package]
name = "c2"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
base64 = { workspace = true }
common = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
